User
Qu1etboy/db-for-ku-home pull request #7
Opened 2023-02-28 18:51 UTC by IceSarun

create 100%
insert 100%
select 30%

2023-02-28 18:56 UTC, IceSarun commented
ทำ select user ข้อที่เหลือไม่ได้ 
1. เราไม่ได้เก็บ Date เพราะฉะนั้นจึงเลือก select เฉพาะลูกค้าที่มาเข้าพักเมื่อปีที่แล้วไม่ได้
2. ค้นหาด้วย id_card คือยังไง (มองเงื่อนไขในการเลือกดูข้อมูลไม่ออก)

2023-03-01 04:29 UTC, Qu1etboy commented
1. เปลี่ยนเป็นแสดง user ทั้งหมดแทน เช่น
```sql
SELECT * FROM User;
```

2. ค้นหาด้วย id_card คือเลือก user ที่สนใจโดยใช้บัตรประชาชน เช่น
```sql
SELECT * FROM User 
Where id_card="...";
```

2023-03-01 04:32 UTC, Qu1etboy requested changes

2023-03-01 04:32 UTC, Qu1etboy commented on insertUser.sql
> +VALUES ('1410406860001','0899947785','ศรชัย','สมบูรณ์','sornchaiSB@gmail.com','#SIlover2023',NULL);
ตรงนี้สามารถลดรูปได้เป็น
```sql
INSERT INTO USER
VALUES
      ('6410406878000','0948576867','ศรันย์ภวัต','	โพธิ์สร้อย','sarunpawat.p@ku.th','#Icekung52','yes'),
      ('1410406860001','0899947785','ศรชัย','สมบูรณ์','sornchaiSB@gmail.com','#SIlover2023',NULL);
```
เป็นต้น

2023-03-01 04:48 UTC, Qu1etboy requested changes

2023-03-01 04:48 UTC, Qu1etboy commented on user.sql
> +(id_card VARCHAR (13),
id_card ใช้เป็น `CHAR(13)` ละกันเพราะความยาวมันคงที่

2023-03-01 05:39 UTC, Qu1etboy commented
อย่าลืมติ้กใน readme ว่าทําแล้วด้วยนะ

2023-03-01 10:50 UTC, IceSarun commented on insertUser.sql
> +VALUES ('1410406860001','0899947785','ศรชัย','สมบูรณ์','sornchaiSB@gmail.com','#SIlover2023',NULL);
Okiee

2023-03-01 10:51 UTC, IceSarun commented on user.sql
> +(id_card VARCHAR (13),
เปลี่ยนใน doc แต่ไม่ได้เปลี่ยนในนี้ 55555555

2023-03-01 11:22 UTC, Qu1etboy approved these changes
👍

2023-03-01 11:23 UTC, merged